---
- name: Download Jolokia source binary
  get_url:
    url: "{{ kafka_jolokia_url }}"
    dest: "{{ kafka_jolokia_lib_dir }}"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0644
